# filepath: /home/msalsouri/Projects/github-pages/_config.yml
title: M AL-SOURI
description: Personal blog and portfolio
url: https://gh.alsouri.co.uk
author:
  name: M AL-SOURI
  email: msalsouri@hotmail.com
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
social:
  twitter: malsouri1
  github: msalsouri
  linkedin: msalsouri
